# Generated by Django 4.0.3 on 2022-06-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_siteuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
