# Generated by Django 4.0.3 on 2022-06-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_siteuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловіча'), ('female', 'Жіноча')], max_length=30, null=True),
        ),
    ]
