# Generated by Django 4.0.3 on 2022-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_siteuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.FileField(blank=True, null=True, upload_to='users/mail/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
