# Generated by Django 4.0.3 on 2022-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mailfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailfiles',
            name='name',
            field=models.CharField(default='mail-templates', max_length=200),
        ),
    ]
