# Generated by Django 4.0.3 on 2022-04-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('trailer_url', models.URLField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('flag_3d', models.BooleanField()),
                ('flag_2d', models.BooleanField()),
                ('flag_imax', models.BooleanField()),
                ('start_sale', models.DateField()),
                ('finish_sale', models.DateField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.gallery')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
