# Generated by Django 4.0.3 on 2022-05-31 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='main/banners/background/')),
                ('background_or_banner', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Background banner',
                'verbose_name_plural': 'Background banner',
            },
        ),
        migrations.CreateModel(
            name='BannersSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_top_banner', models.BooleanField(default=False)),
                ('speed_top_banner', models.PositiveSmallIntegerField(default=5)),
                ('is_active_news_and_promotion', models.BooleanField(default=False)),
                ('speed_news_and_promotion', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Banners page setting',
                'verbose_name_plural': 'Banners page settings',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('title_uk', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
                ('text_uk', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('top_banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('condition', models.TextField()),
                ('condition_uk', models.TextField(null=True)),
                ('condition_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('title_uk', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
                ('text_uk', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('flag_3d', models.BooleanField(verbose_name='3D')),
                ('flag_2d', models.BooleanField(verbose_name='2D')),
                ('flag_imax', models.BooleanField(verbose_name='IMAX')),
                ('seats_config', models.CharField(max_length=50, verbose_name='Simple seats config')),
                ('vip_seats_config', models.CharField(blank=True, max_length=50, null=True, verbose_name='VIP seats config')),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.cinema')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gallery')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
            },
        ),
        migrations.CreateModel(
            name='MainNewsAndPromotionsBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='main/banners/news_and_promotions/')),
                ('banner_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News/promotion banner',
                'verbose_name_plural': 'News and promotions banners',
            },
        ),
        migrations.CreateModel(
            name='MainTopBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='main/banners/top/')),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('banner_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Top banner',
                'verbose_name_plural': 'Top banners on main page',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('title_uk', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
                ('text_uk', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('flag_3d', models.BooleanField(verbose_name='3D')),
                ('flag_2d', models.BooleanField(verbose_name='2D')),
                ('flag_imax', models.BooleanField(verbose_name='IMAX')),
                ('trailer_url', models.URLField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('start_sale', models.DateField()),
                ('finish_sale', models.DateField()),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gallery')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_url', models.URLField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('title_uk', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
                ('text_uk', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('non_delete_page', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, default='other_page', max_length=30, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gallery')),
                ('seo_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seoblock')),
            ],
            options={
                'verbose_name': 'Base page',
                'verbose_name_plural': 'Base pages',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_3d', models.BooleanField(verbose_name='3D')),
                ('flag_2d', models.BooleanField(verbose_name='2D')),
                ('flag_imax', models.BooleanField(verbose_name='IMAX')),
                ('start', models.DateTimeField()),
                ('seats_reserved', models.CharField(blank=True, max_length=50, null=True)),
                ('seats_busy', models.CharField(blank=True, max_length=50, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.movie')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seoblock'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('phone_1', models.CharField(max_length=25)),
                ('phone_2', models.CharField(blank=True, max_length=25, null=True)),
                ('main_seo_text', models.TextField()),
                ('main_seo_text_uk', models.TextField(null=True)),
                ('main_seo_text_ru', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('seo_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seoblock')),
            ],
            options={
                'verbose_name': 'Main page',
                'verbose_name_plural': 'Main page',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gallery')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seoblock'),
        ),
        migrations.CreateModel(
            name='CinemaContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('title_uk', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=150)),
                ('address_uk', models.CharField(max_length=150, null=True)),
                ('address_ru', models.CharField(max_length=150, null=True)),
                ('coordinates', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('seo_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seoblock')),
            ],
            options={
                'verbose_name': 'Cinema contacts',
                'verbose_name_plural': 'Cinemas contacts',
            },
        ),
        migrations.AddField(
            model_name='cinema',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gallery'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seoblock'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('title_uk', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
                ('text_uk', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('article_type', models.CharField(blank=True, max_length=20, null=True)),
                ('video_url', models.URLField(verbose_name='Video')),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gallery')),
                ('seo_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.seoblock')),
            ],
            options={
                'verbose_name': 'News and promotions',
                'verbose_name_plural': 'News and promotions',
            },
        ),
    ]
