# Generated by Django 4.0.3 on 2022-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_is_active_news_and_promotion_bannerssettings_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundbanner',
            name='background_or_banner',
            field=models.CharField(choices=[('banner', 'Фото на фоні'), ('background', 'Просто фон')], default='background', max_length=30),
        ),
    ]
