# Generated by Django 4.0.3 on 2022-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_backgroundbanner_background_or_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemacontacts',
            name='coordinates',
            field=models.CharField(max_length=600),
        ),
    ]
