# Generated by Django 4.0.3 on 2022-04-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='flag_2d',
            field=models.BooleanField(verbose_name='2D'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='flag_3d',
            field=models.BooleanField(verbose_name='3D'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='flag_imax',
            field=models.BooleanField(verbose_name='IMAX'),
        ),
    ]
