# Generated by Django 4.0.3 on 2022-04-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_movie_flag_2d_alter_movie_flag_3d_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cinema',
        ),
    ]
