# Generated by Django 4.0.3 on 2022-04-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('flag_3d', models.BooleanField(verbose_name='3D')),
                ('flag_2d', models.BooleanField(verbose_name='2D')),
                ('flag_imax', models.BooleanField(verbose_name='IMAX')),
                ('seats_reserved', models.CharField(max_length=50)),
                ('seats_busy', models.CharField(max_length=50)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.movie')),
            ],
            options={
                'verbose_name': 'Hall',
                'verbose_name_plural': 'Halls',
            },
        ),
    ]
