# Generated by Django 4.0.3 on 2022-04-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
