# Generated by Django 4.0.3 on 2022-04-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_session_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery'},
        ),
    ]
