# Generated by Django 4.0.3 on 2022-04-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_gallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesitepage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
