# Generated by Django 4.0.3 on 2022-04-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
