# Generated by Django 4.0.3 on 2022-04-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_basesitepage_gallery_cinema_gallery_hall_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesitepage',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basesitepage',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basesitepage',
            name='gallery',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='gallery',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gallery',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
    ]
