# Generated by Django 4.0.3 on 2022-04-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_basesitepage_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesitepage',
            name='gallery',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='gallery',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gallery',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapp.gallery'),
        ),
    ]
