# Generated by Django 4.0.3 on 2022-04-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_gallery_remove_basesitepage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesitepage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='gallery',
        ),
        migrations.AddField(
            model_name='basesitepage',
            name='image',
            field=models.ManyToManyField(to='adminapp.image'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ManyToManyField(to='adminapp.image'),
        ),
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ManyToManyField(to='adminapp.image'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ManyToManyField(to='adminapp.image'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
