# Generated by Django 4.0.3 on 2022-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_alter_basesitepage_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesitepage',
            name='main_image',
            field=models.ImageField(blank=True, default='bsimg.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='main_image',
            field=models.ImageField(blank=True, default='bsimg.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hall',
            name='main_image',
            field=models.ImageField(blank=True, default='bsimg.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_image',
            field=models.ImageField(blank=True, default='bsimg.jpeg', null=True, upload_to=''),
        ),
    ]
