# Generated by Django 4.0.3 on 2022-04-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_alter_basesitepage_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basesitepage',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='seo_keywords',
        ),
    ]
