# Generated by Django 4.0.3 on 2022-04-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_remove_basesitepage_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesitepage',
            name='seo_keywords',
            field=models.TextField(default='qwe'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_keywords',
            field=models.TextField(default='qwe'),
        ),
        migrations.AddField(
            model_name='hall',
            name='seo_keywords',
            field=models.TextField(default='qwe'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_keywords',
            field=models.TextField(default='qwe'),
        ),
    ]
