# Generated by Django 4.0.3 on 2022-05-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0034_cinema_top_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.cinema'),
        ),
    ]
