# Generated by Django 4.0.3 on 2022-05-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_alter_hall_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='vip_seats_config',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VIP seats config'),
        ),
        migrations.AlterField(
            model_name='session',
            name='seats_busy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='seats_reserved',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
