# Generated by Django 4.0.3 on 2022-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0037_alter_basesitepage_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesitepage',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
